### ISSUE TITLE
Explicit "Spacing" in the grammar should be delegated to the lexer

### ISSUE THREAD

**Issue by cmr** [adambadawy/ScarfTemp#1]
Generally when creating a formal language, you distinguish between lexical elements and syntactic constructs. One practical reason is that, at the character level, many languages aren't context free (the ["maximal munch"](https://en.wikipedia.org/wiki/Maximal_munch) convention is typically the cause). But, lexers can often be much more efficient than the equivalent infrastructure encoded into the whole parser, because their task is much more limited. One of the responsibilities of the lexer would be skipping over comments and whitespace, making it unnecessary to specify where exactly "spacing" can occur.

**Comment by adambadawy** [comment]
Thanks for the insight! I was wondering about this, actually. I'll edit the grammar accordingly.

**Comment by adambadawy** [comment]
Resolved by f6f0a89.
